language: node_js
node_js:
  - "node"
  - "8"
before_install:
  - npm i -g npm@5.6.0
deploy:
  provider: heroku
  app: rearn-flashcard-app
  api_key:
    secure: "77443ae5-06d5-4f0f-96a6-d610737f84b8"